### ISSUE TITLE
4. NPM

### ISSUE THREAD

**Issue by esfrankel** [MakeSchool-Tutorials/sa-2018-rotten-potatoes#1]
I had to use `npm install -g nodemon` for nodemon to start in the rotten_potatoes folder. Might have just been the way I set it up though.

**Comment by joerez** [comment]
Hey! 

I'm going to submit a pull request that changes it to that specifically, because we want to use nodemon globally anyways.

Thanks!

**Comment by dionlarson** [comment]
Fixed
