### ISSUE TITLE
4. NPM

### ISSUE THREAD

**Issue by dacasanovat** [MakeSchool-Tutorials/sa-2018-rotten-potatoes#10]
In the following pictures I found some errors:

<img width="1047" alt="captura de pantalla 2018-07-05 a la s 1 09 29 p m" src="https://user-images.githubusercontent.com/31299884/42346106-586d3b84-8056-11e8-8602-4b6e7ead8f30.png">
<img width="1054" alt="captura de pantalla 2018-07-05 a la s 1 12 24 p m" src="https://user-images.githubusercontent.com/31299884/42346108-59ec8e24-8056-11e8-817c-f3e883b64de0.png">
<img width="1036" alt="captura de pantalla 2018-07-05 a la s 1 04 51 p m" src="https://user-images.githubusercontent.com/31299884/42346112-5bd5519e-8056-11e8-9a74-b312ad398da1.png">

first picture:
 In the  first sentence I think the word "out" is supposed to be "our".
second picture:
There is a "use" after "won't" missing.
third picture:
The "dependencies" part is our of format.

**Comment by dionlarson** [comment]
Fixed
