### ISSUE TITLE
6. REST

### ISSUE THREAD

**Issue by dacasanovat** [MakeSchool-Tutorials/sa-2018-rotten-potatoes#11]
in the following picture:

<img width="583" alt="captura de pantalla 2018-07-05 a la s 2 08 01 p m" src="https://user-images.githubusercontent.com/31299884/42350914-6a17ae08-8067-11e8-9ad8-d82fc97244bb.png">
<img width="563" alt="captura de pantalla 2018-07-05 a la s 2 04 52 p m" src="https://user-images.githubusercontent.com/31299884/42350915-6b7af822-8067-11e8-9991-e2e880e86f9b.png">

First picture:
We are missing a "think" I believe.
Second picture: 
in the first sentence we are missing a "to" I believe.

**Comment by dionlarson** [comment]
Fixed
