### ISSUE TITLE
8. Writing To MongoDB

### ISSUE THREAD

**Issue by dacasanovat** [MakeSchool-Tutorials/sa-2018-rotten-potatoes#12]
In the following pictures:

<img width="628" alt="captura de pantalla 2018-07-05 a la s 3 48 54 p m" src="https://user-images.githubusercontent.com/31299884/42394621-9cb0d3dc-810f-11e8-8ba3-31a9c9a264cb.png">
<img width="495" alt="captura de pantalla 2018-07-06 a la s 9 53 00 a m" src="https://user-images.githubusercontent.com/31299884/42394624-9e580e58-810f-11e8-855b-fe3252d96afe.png">

First picture:
There is an error in the first sentence. It doesn't make sense. It is missing a word
Second picture:
There is an error in no.4 I think there is a typo.

**Comment by dionlarson** [comment]
Fixed
