### ISSUE TITLE
9. Reading From MongoDB

### ISSUE THREAD

**Issue by dacasanovat** [MakeSchool-Tutorials/sa-2018-rotten-potatoes#13]
In the following picture:
<img width="574" alt="captura de pantalla 2018-07-06 a la s 1 37 08 p m" src="https://user-images.githubusercontent.com/31299884/42401385-4041c44c-812a-11e8-9c79-963027dad067.png">

There is a typo in the code...{{this._id}} should be without the underscore.

**Comment by dionlarson** [comment]
Fixed
