### ISSUE TITLE
9. Reading From MongoDB

### ISSUE THREAD

**Issue by esfrankel** [MakeSchool-Tutorials/sa-2018-rotten-potatoes#7]
Again, this might just be me, but in the code snippet describing the post method to redirect to your review was messed up.

`router.post('/reviews', (req, res) => {
  const review = new Review(req.body);

  review.save(function(err, review) {
    if (err) {
      console.log(err);
    }

    // 1
    return res.redirect('/reviews/' + review._id);
  });
});`

I consistently got an error when I tried to call review._id, but when I changed it to .id, it worked.

**Comment by dionlarson** [comment]
Fixed
