### ISSUE TITLE
3. Hello World

### ISSUE THREAD

**Issue by dacasanovat** [MakeSchool-Tutorials/sa-2018-rotten-potatoes#8]
In the following picture:
<img width="1112" alt="captura de pantalla 2018-07-05 a la s 11 41 08 a m" src="https://user-images.githubusercontent.com/31299884/42345445-3497bb78-8054-11e8-9dc3-4546bdf53a98.png">

there is a typo in the word "being" it says "begin".

**Comment by dionlarson** [comment]
Fixed
