### ISSUE TITLE
3. Hello World

### ISSUE THREAD

**Issue by dacasanovat** [MakeSchool-Tutorials/sa-2018-rotten-potatoes#9]
In the following picture: 

<img width="1122" alt="captura de pantalla 2018-07-05 a la s 11 33 18 a m" src="https://user-images.githubusercontent.com/31299884/42345492-579e005a-8054-11e8-9e82-deecd1bfa636.png">
Please explain the bug you found here.

There is a typo in the second sentence, I believe the word "out" is supposed to be "our".

**Comment by dionlarson** [comment]
Fixed
